"""Add employee link to user model

Revision ID: 75d622be9af6
Revises: a2e8c6aa4d66
Create Date: 2025-07-30 16:42:15.139629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75d622be9af6'
down_revision = 'a2e8c6aa4d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_log')
    op.drop_table('alert')
    op.drop_table('leave_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('proposed_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('proposed_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('leave_request_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_request_pkey'))
    )
    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    op.create_table('attendance_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('attendance_log_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_log_pkey'))
    )
    # ### end Alembic commands ###
