"""Initial migration

Revision ID: a2e8c6aa4d66
Revises: 
Create Date: 2025-07-30 15:52:14.631628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2e8c6aa4d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suivi_journalier_image')
    op.drop_table('vinish_database_image')
    op.drop_table('suivi_journalier')
    op.drop_table('time_sheet_entry')
    op.drop_table('time_sheet')
    op.drop_table('new_suivi_journalier_image')
    op.drop_table('vinish_database')
    op.drop_table('alert')
    op.drop_table('new_suivi_journalier')
    op.drop_table('db_user')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipment_assigned_client_id_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_client_id')

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('proposed_end_date', sa.Date(), nullable=True))
        batch_op.drop_column('reason')
        batch_op.drop_column('requested_at')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('service_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('proposed_end_date')
        batch_op.drop_column('proposed_start_date')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('equipment_assigned_client_id_fkey'), 'client', ['assigned_client_id'], ['id'])

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('db_user',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('db_user_pkey'))
    )
    op.create_table('new_suivi_journalier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('new_suivi_journalier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('utilisateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_date_reception', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_quantite', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_type_raccord', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_valeur_resistance', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_dctires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_actires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_terretires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_courant_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_ac', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_puissance', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_technicien', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_profondeur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shelter_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('problems', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='new_suivi_journalier_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    op.create_table('vinish_database',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vinish_database_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('utilisateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nom_du_chantier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chantier_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interconnexion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nombre_panneaux', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_rail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipement_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_date_reception', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('connecteur_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_quantite', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_profondeur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shelter_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('onduleur_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('onduleur_details_avancement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('heure_de_travail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cables_dctires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_actires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_terretires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('problems', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fin_zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_courant_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_ac', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_puissance', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_technicien', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vinish_database_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('new_suivi_journalier_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suivi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suivi_id'], ['new_suivi_journalier.id'], name=op.f('new_suivi_journalier_image_suivi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('new_suivi_journalier_image_pkey'))
    )
    op.create_table('time_sheet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('check_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('time_sheet_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_sheet_pkey'))
    )
    op.create_table('time_sheet_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('time_sheet_entry_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_sheet_entry_pkey'))
    )
    op.create_table('suivi_journalier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('suivi_journalier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chantier_du_jour', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipe_presente', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('heures_travail', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('materiel_livre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('travaux_realises', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('problemes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('avancement', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('objectif_special', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cable_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cable_ac', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nombre_rail', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pose_onduleur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cable_terre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo_chantier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('utilisateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='suivi_journalier_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vinish_database_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suivi_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['suivi_entry_id'], ['vinish_database.id'], name=op.f('vinish_database_image_suivi_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vinish_database_image_pkey'))
    )
    op.create_table('suivi_journalier_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suivi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suivi_id'], ['suivi_journalier.id'], name=op.f('suivi_journalier_image_suivi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('suivi_journalier_image_pkey'))
    )
    # ### end Alembic commands ###
