"""modify Equipment

Revision ID: a86f20ab720b
Revises: add_fields_to_equipment
Create Date: 2025-08-01 16:38:17.538427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86f20ab720b'
down_revision = 'add_fields_to_equipment'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vinish_database_image')
    op.drop_table('leave_request')
    op.drop_table('vinish_database')
    op.drop_table('user_account')
    op.drop_table('attendance_log')
    op.drop_table('db_user')
    op.drop_table('alert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    op.create_table('db_user',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('db_user_pkey'))
    )
    op.create_table('attendance_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('attendance_log_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_log_pkey'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_account_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_account_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('vinish_database',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vinish_database_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('utilisateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nom_du_chantier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chantier_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('equipement_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_date_reception', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('connecteur_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_quantite', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_profondeur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('onduleur_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelter_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cables_dctires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_actires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_terretires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('onduleur_details_avancement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('heure_de_travail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interconnexion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nombre_panneaux', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_rail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('problems', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fin_zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_courant_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_ac', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_puissance', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_technicien', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vinish_database_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('leave_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('proposed_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('proposed_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('leave_request_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_request_pkey'))
    )
    op.create_table('vinish_database_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suivi_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['suivi_entry_id'], ['vinish_database.id'], name=op.f('vinish_database_image_suivi_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vinish_database_image_pkey'))
    )
    # ### end Alembic commands ###
