"""Add category to Equipment

Revision ID: aae6d95ca4cb
Revises: dc5fea27b759
Create Date: 2025-08-01 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae6d95ca4cb'
down_revision = 'dc5fea27b759' # Assurez-vous que ceci correspond au 'revision' du fichier précédent
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('category', sa.String(length=50), nullable=False, server_default='Materiels'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'category')
    # ### end Alembic commands ###
