"""Add employee_id to user table

Revision ID: dc5fea27b759
Revises: 75d622be9af6
Create Date: 2025-07-31 10:32:53.692100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc5fea27b759'
down_revision = '75d622be9af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('vinish_database')
    #op.drop_table('vinish_database_image')
    #op.drop_table('db_user')
    #op.drop_table('leave_request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    op.create_table('leave_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('proposed_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('proposed_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('leave_request_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_request_pkey'))
    )
    op.create_table('db_user',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('db_user_pkey'))
    )
    op.create_table('vinish_database_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suivi_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['suivi_entry_id'], ['vinish_database.id'], name=op.f('vinish_database_image_suivi_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vinish_database_image_pkey'))
    )
    op.create_table('vinish_database',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('utilisateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nom_du_chantier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chantier_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('equipement_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_date_reception', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('equipement_nombre_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('connecteur_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_quantite', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connecteur_etat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chemin_cable_profondeur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('terre_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cableac_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabledc_longueur', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('onduleur_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelter_nombre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cables_dctires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_actires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cables_terretires', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('equipe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('onduleur_details_avancement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('heure_de_travail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interconnexion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nombre_panneaux', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_rail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('problems', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fin_zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_courant_dc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_tension_ac', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_puissance', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_technicien', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fin_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vinish_database_pkey'))
    )
    # ### end Alembic commands ###
